version: "2"
run:
  relative-path-mode: wd
linters:
  default: none
  enable:
    - depguard
    - errcheck
    - godox
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/bold-minds/txt
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
issues:
  max-same-issues: 50
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
